### ISSUE TITLE
Ngr error

### ISSUE THREAD

**Issue by itdoster** [steveblue/angular2-rollup#36]
I am getting this error, mac os: 
NGR ERROR { Error: Cannot find module './../cli.config.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-rollup/src/log.js:12:21)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }

NGR ERROR 1

**Comment by steveblue** [comment]
What version of angular-rollup are you on @itdoster? It is awfully hard to help without any context.

**Comment by itdoster** [comment]
@steveblue 2.0.4
